- hosts: bastion  
  tasks:
   - name: include variables
     ansible.builtin.include_vars: 
      file: ./variables/var_run_backup.yaml
   - name: include tasks
     ansible.builtin.include_vars: 
      file: ./tasks/run_Backup.yaml
     
