- hosts: bastion

  tasks:     
  
   - name: include vault for secrets 
     include_vars: ./vaults/vault_backup.yaml
     
   - name: include  variables
     include_vars: ./variables/var_backup.yaml
     
   - import_tasks: ./tasks/config_Backup.yaml
