name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: ansible/playbook.yaml # path to your Ansible playbook
          directory: ./
          key: ${{ secrets.ansible_ssh_private_key }} 
