name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      
    - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
      uses: ansible-community/ansible-lint-action@main
        
  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/ansible
      with: 
        playbook: playbook.yml
        inventory: localhost
