name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Testing action
        uses: ./
        with:
          playbook: ansible/playbook.yaml
          inventory: ansible/hosts
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false"
