name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    #- name: Lint Ansible Playbook
   # uses: ansible/ansible-lint-action@main

    - name: Setup Python  
      uses: actions/setup-python@v3
      with:  
        python-version: 3.10.0  
        architecture: x64      
    - run: python my_script.py
  
  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./actions/ansible
      with: 
        playbook: playbook.yaml
        inventory: hosts
