name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
        
  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Play Ansible Playbook
      uses: arillso/action.playbook@master
      with:
        playbook: tests/playbook.yml
        inventory: tests/hosts.yml
        galaxy_file: tests/requirements.yml
      env:
       ANSIBLE_HOST_KEY_CHECKING: 'false'
       ANSIBLE_DEPRECATION_WARNINGS: 'false'
