name: deploy ansible playbook

on:
  pull_request:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

  deployAnsible:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v3

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: playbook.yaml
        # Optional, directory where playbooks live
        directory: ansible
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}
        # Optional, encrypted vault password
        vault_password: ${{secrets.VAULT_PASSWORD}}
        # Optional, literal inventory file contents
        options: |
          --inventory ./hosts
