name: deploy ansible

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  test_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build Docker image
        run: docker build --pull -t test .

      - name: Test Docker image
        run: docker image inspect test

  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Testing action
        uses: ./
        with:
          playbook: ansible/playbook.yaml
          inventory: ansbile/hosts
        env:
          ANSIBLE_HOST_KEY_CHECKING: "false"
          ANSIBLE_DEPRECATION_WARNINGS: "false"
